# Generated by Django 5.1 on 2024-09-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('published_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('cover', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
